code review
WhoIsYgim/matrix_calc pull request #1
Opened 2022-10-16 21:08 UTC by WhoIsYgim

2022-10-29 09:33 UTC, Denactive requested changes
Отличная домашка.
Поправь то, на что указал. Особенно по сиай. В example привели какой-нибудь расчет с матрицами.

не увидел слайсы. Тут полная свобода творчества, если что, обращайся за подсказками.

На исправления и допы есть неделя (до 04.11.22)

сдал в последний час. Лучше так не делать :3

2022-10-29 09:33 UTC, Denactive commented on .github/workflows/ci.yml
> +
нормальный сиай, только в артефакт билда попал весь проект, и он весит 10 Мб, хотя по логике нужно грузить только бинарник или какой-нибудь архив
![image](https://user-images.githubusercontent.com/70894930/198823419-ee6b8af3-67b2-42b4-9c0a-61877534b677.png)

Выгрузи во второй джобе отчет о покрытии. В PR > вкладка checks можно добавить бейджик в репо гитзаб с процентом покрытия. Сделай бейджик, если будет интересно

2022-10-29 09:33 UTC, Denactive commented on .gitignore
> +Testing
проставь \n в конце всех файлов

2022-10-29 09:33 UTC, Denactive commented on include/matrix_calc/matrix.h
> +        std::size_t cols_;
расширяемая матрица. необычно

2022-10-29 09:33 UTC, Denactive commented on include/matrix_calc/matrix.h
> +    template<size_t M, size_t N = M>
круто. Мб вынести в отдельный класс. Файлы одновременно объявляющие такие штуки и их реализацию называют hpp. Необходимость, когда работаешь с шаблонными классами

2022-10-29 09:33 UTC, Denactive commented on include/matrix_calc/vector.h
> +    class IVector{
лайк за интерфейс

2022-10-29 09:33 UTC, Denactive commented on include/matrix_calc/matrix.h
> +        vector main_diagonal();
я бы сделал vector diagonal(secondary = false);

2022-10-29 09:33 UTC, Denactive commented on src/matrix.cpp
> +    : cols_(n), rows_(m),
возможна ли матрица размерности [0 x 0] ? сделай проверку

2022-10-29 09:33 UTC, Denactive commented on src/matrix.cpp
> +    matrix matrix::inverse() {
Это было необязательно, но лайк.

2022-10-29 09:33 UTC, Denactive commented on src/matrix.cpp
> +                (*this*out).determinant() -1 ) >= eps){
пробелы: `while (std::abs((*this*out).determinant() - 1) >= eps)`
я бы eps либо задавал парметром, либо сделал бы глобальным.
Это похоже на метод Гаусса, респект.
Но операции 
```
            out = *this*prev;
            out *= -1;
            out += E;
            out = prev*out;
```
неочевидны, и ты можешь записать это одной строкой

можешь коротко пояснить, почему ты итерируешься до тех пор, пока определитель не станет единицей? Разве det(m) -> m == E ? Мб в методе Гаусса есть какие-то дополнительные критерии строгости, о которых я не слышал.

2022-10-29 09:33 UTC, Denactive commented on src/matrix.cpp
> +    : cols_(n), rows_(m),
хотя, она у тебя расширяемая и все такое. Хотя зачем возможность создания матрицы 0х0. Можно создавать 1х1 по умолчанию и сделать все параметры этого конструктора необязательными

2022-11-01 12:09 UTC, ygimm commented on src/matrix.cpp
> +                (*this*out).determinant() -1 ) >= eps){
я использовал итерационный метод вычисления обратной матрицы.
по гауссу считал определитель.

2022-11-01 12:15 UTC, WhoIsYgim commented on src/matrix.cpp
> +                (*this*out).determinant() -1 ) >= eps){
оставил в коде комментарий с итерационной формулой

2022-11-03 09:51 UTC, Denactive requested changes
мне домашка нравится несмотря на в общем то небольшое дублирование кода в колонка/строках.
еще есть время сделать слайсы

2022-11-03 09:51 UTC, Denactive commented on examples/example_1.cpp
> +*/
прикольно )

2022-11-03 09:51 UTC, Denactive commented on src/row.cpp
> +    {}
у этого класса и у вектора-колонки очень много одинаковых методов. Можно вынести однотипную реализацию в тот класс который уу тебя пока является интерфейсом

2022-11-03 09:51 UTC, Denactive commented on src/row.cpp
> +        if(size_ != rhs.size_){
тогда такие опреаторы будут принимать const Vector& или const Vector*

2023-06-04 13:00 UTC, merged